name: Bump Usaneo Version

on:
  schedule:
    - cron: '0 0 * * *'  # Esegue ogni giorno a mezzanotte UTC
  workflow_dispatch:  # Permette esecuzione manuale

permissions:
  contents: write  # Permesso per commit

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      # Checkout del codice
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Configura Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # Aggiorna la versione in __version__.
      # Crea un commit
      - name: Commit changes
        run: |
          git add __version__.py
          git commit -m "chore: bump version to $(python -c 'import re; print(re.search(r\'VERSION = \"(.*?)\"', open(\'__version__.py\').read()).group(1))')" || echo "No changes to commit"
          git push origin main
